### ISSUE TITLE
feat: add publish to scm provider

### ISSUE THREAD

**Issue by Sam42R** [Sam42R/semver-maven-plugin#10]
# Description

ScmProvider should be expanded with ability to push changes to remote repository.

# Tasks
- [x] update ScmProvider interface
- [x] impl git reference provider
- [x] update mojo to push to remote
  - [x] add featue flag to maven plugin
