### ISSUE TITLE
build: maven profile for bundle generation

### ISSUE THREAD

**Issue by Sam42R** [Sam42R/semver-maven-plugin#11]
# Description

The bundle generation for maven central publishing should be collected into own maven profile.

# Tasks

- [x] create profile
  - [x] move source and javadoc creation
  - [x] move jar signing
  - [x] call bundle script with e.g. maven-ant-plugin
