### ISSUE TITLE
feat: semver-release-api

### ISSUE THREAD

**Issue by Sam42R** [Sam42R/semver-maven-plugin#24]
# Description 

In order to create a release for the semantic version based tag we need a new module type: semver-release-api

As provider we may support:
- GitHub
- Gitlab
- optional: Bitbucket Dowloads?

# Tasks

- [x] create semver-release-api
- [x] create github provider
- [x] create gitlab provider
- [ ] optional: create bitbucket provider

# Resources

- [Github](https://docs.github.com/de/rest/releases/releases?apiVersion=2022-11-28)
- [Gitlab](https://docs.gitlab.com/ee/api/releases/)
- [Bitbucket Downloads](https://support.atlassian.com/bitbucket-cloud/docs/deploy-build-artifacts-to-bitbucket-downloads/)
