### ISSUE TITLE
bug: set version pattern

### ISSUE THREAD

**Issue by Sam42R** [Sam42R/semver-maven-plugin#31]
# Description

Semantic version number set in `pom.xml` should always follow: `Major.Minor.Patch`

The existing `versionPattern` config defaulting to
use prefix `v` should only used for tag creation.

# Tasks

- [ ] refactor `versionPattern` to `tagFormat`
- [ ] always set plain semantic version number
- [ ] use named placeholders for `tagFormat` configuration

# Resources
- [semantic-release - configuration](https://semantic-release.gitbook.io/semantic-release/usage/configuration)
- [named placeholders in string formatting](https://www.baeldung.com/java-string-formatting-named-placeholders)
