### ISSUE TITLE
feat: html changelog renderer

### ISSUE THREAD

**Issue by Sam42R** [Sam42R/semver-maven-plugin#42]
# Description

This issue is about providing html renderer for changelog.

# Tasks

- [x] add html changelog renderer
  - [x] support different templates
- [ ] take care for white space
  - see [Thymeleaf Extras](https://github.com/connect-group/thymeleaf-extras) 

# Resources

- https://codepen.io/aolko/pen/ROPpvv
- https://codepen.io/Lachgas7778/pen/vVRwyX
- https://spinalcms.com/resources/basic-saas-changelog-with-tailwind/
- https://missiveapp.com/blog/changelog-growth-tool
