### ISSUE TITLE
feat: changelog renderer as plugin

### ISSUE THREAD

**Issue by Sam42R** [Sam42R/semver-maven-plugin#9]
# Description

changelog-renderer-api should be load as plugin (ServiceLoader).

# Tasks
- [x] add maven plugin config parameter
- [x] update `ChangelogRender` interface
- [x] load with ServiceLoader
